"""initial revision

Revision ID: 0da05cbf693f
Revises:
Create Date: 2024-12-28 03:34:41.201699

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0da05cbf693f"
down_revision: str | None = None
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    """Upgrade to '0da05cbf693f'"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mailings",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.String(), nullable=False),
        sa.Column("name", sqlmodel.String(), nullable=False),
        sa.Column("is_validated", sa.Boolean(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_subscribed", sa.Boolean(), nullable=False),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="email",
    )
    op.create_index(op.f("ix_email_mailings_created_at"), "mailings", ["created_at"], unique=False, schema="email")
    op.create_index(op.f("ix_email_mailings_email"), "mailings", ["email"], unique=True, schema="email")
    op.create_index(op.f("ix_email_mailings_updated_at"), "mailings", ["updated_at"], unique=False, schema="email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade to None"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_mailings_updated_at"), table_name="mailings", schema="email")
    op.drop_index(op.f("ix_email_mailings_email"), table_name="mailings", schema="email")
    op.drop_index(op.f("ix_email_mailings_created_at"), table_name="mailings", schema="email")
    op.drop_table("mailings", schema="email")
    # ### end Alembic commands ###
