"""initial revision

Revision ID: 83367e99b9c5
Revises:
Create Date: 2024-12-28 03:35:13.760837

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "83367e99b9c5"
down_revision: str | None = None
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    """Upgrade to '83367e99b9c5'"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "downloads",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.String(), nullable=False),
        sa.Column("name", sqlmodel.String(), nullable=False),
        sa.Column("link", sqlmodel.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_downloaded", sa.Boolean(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("presigned_url", sqlmodel.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="download",
    )
    op.create_index(op.f("ix_download_downloads_created_at"), "downloads", ["created_at"], unique=False, schema="download")
    op.create_index(op.f("ix_download_downloads_email"), "downloads", ["email"], unique=False, schema="download")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade to None"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_download_downloads_email"), table_name="downloads", schema="download")
    op.drop_index(op.f("ix_download_downloads_created_at"), table_name="downloads", schema="download")
    op.drop_table("downloads", schema="download")
    # ### end Alembic commands ###
