---
services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DEBUG: ${DEBUG:-1}
      DOCKER_HOST: unix:///var/run/docker.sock
      LS_LOG: WARN
      HOSTNAME: localstack
      LOCALSTACK_HOST: localstack
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:4566 || exit 1
      interval: 3s
      retries: 30
      start_period: 20s
      timeout: 120s

  postgres-db:
    image: postgres:16.2
    user: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 30s
      timeout: 120s
      retries: 15
      start_period: 20s

  download_service:
    container_name: download_service
    build:
      context: ./functions/download_service
      dockerfile: Dockerfile.local
    volumes:
      - ".:/home/code"
      - ".venv.docker:/home/code/.venv"
    ports:
      - 5001:5001
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
      - postgres-db
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:5001/health || exit 1
      interval: 60s
      retries: 30
      start_period: 20s
      timeout: 120s

  reader_service:
    container_name: reader_service
    build:
      context: ./functions/reader_service
      dockerfile: Dockerfile.local
    volumes:
      - "./functions/reader_service:/home/code"
      - "./functions/reader_service/.venv.docker:/home/code/.venv"
    ports:
      - 5002:5002
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
      - postgres-db

  email_service:
    container_name: email_service
    build:
      context: ./functions/email_service
      dockerfile: Dockerfile.local
    volumes:
      - "./functions/email_service:/home/code"
      - "./functions/email_service/.venv.docker:/home/code/.venv"
    ports:
      - 5003:5003
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
      - postgres-db

volumes:
  postgres-db-volume:
    driver: local
